{"name": "test_one[错误]", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_calc.py:21: AssumptionFailure\n>>\tpytest.assume(result == get_add_dates[2])\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_calc.py:21: AssumptionFailure\nE               >>\tpytest.assume(result == get_add_dates[2])\nE               AssertionError: assert False\n\n..\\..\\..\\AppData\\Roaming\\Python\\Python38\\site-packages\\six.py:702: FailedAssumption"}, "steps": [{"name": "此处为第二个执行", "status": "passed", "start": 1607844301585, "stop": 1607844301585}], "attachments": [{"name": "stdout", "source": "bc73e1ab-69f6-48e2-b80f-0495127d0bec-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_add_dates", "value": "['错误', 1, '空格']"}], "start": 1607844301584, "stop": 1607844301582, "uuid": "4e54f4e8-d2d6-41fd-ae16-2d7cd176f18a", "historyId": "f88c4016b35947aa88e73f135ba1f062", "testCaseId": "5b53a6327a2dd636b4220af42ad90cc9", "fullName": "test_calc.TestCalc#test_one", "labels": [{"name": "feature", "value": "类的allure"}, {"name": "tag", "value": "flaky(reruns=1, reruns_delay=1)"}, {"name": "tag", "value": "run(order=2)"}, {"name": "tag", "value": "add"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "LAPTOP-2NSHDHR9"}, {"name": "thread", "value": "4024-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}